name: Milton
favicon: null
layout_spectrum: 0.54935
typography_spectrum: 0.50593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00000a'
    - '#a5a38e'
    - '#777662'
    - '#2a4469'
    - '#bc565e'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.7424970043357462
  rhythmicContrast: 1
purpose: []
