favicon: null
name: Milton
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3082437
  brandStrength: 0.6875
  rhythmicContrast: 0.6362007
  brandColors:
    - '#00000a'
    - '#a5a38e'
    - '#777662'
    - '#2a4469'
    - '#bc565e'
  lightness: 0.6612903
typography_spectrum: 0.50593
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9086022
analytics:
  twitter: null
  google: null
  facebook: null
