name: Milton
favicon: null
layout_spectrum: 0.9086022
typography_spectrum: 0.50593
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Patrick Milton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00000a'
    - '#a5a38e'
    - '#777662'
    - '#2a4469'
    - '#bc565e'
  brandStrength: 0.6875
  lightness: 0.6612903
  saturation: 0.3082437
  rhythmicContrast: 0.6362007
purpose: []
